### PR TITLE
[CORE-4290] Update .rubocop.yml

### PR DESCRIPTION
**Pull request by chrt00**
https://lendesk.atlassian.net/browse/CORE-4290

### CODE REVIEW

**Review by suparious — APPROVED** [review]
LGTM

AbcMetric default appears to be 15
MethodLength default is probably 10

**Review by mrleeio — COMMENTED** [review]
I won't approve or block, I'll let the team decide.

From my perspective these rules exist in an attempt to nudge us towards writing better code.  In my opinion I would rather continue to use the default configuration for these rules.

If you need to disable the rule for some reason (legacy code) you can explicitly disable the rule by using comments.  For example:

```
def some_method # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  # some method that triggers Abcsize and length
end
```

If this is a large file with many broken rules you can disable the rule, but make sure to reenable it at the end.

```
# rubocop:disable Metrics/AbcSize, Metrics/MethodLength

def some_method 
  # some method that triggers Abcsize
end

def some_long_method 
  # some method that triggers method length
end

# rubocop:enable Metrics/AbcSize, Metrics/MethodLength
```

This way the decision to disable these rules are explicit while still encouraging best practices throughout the rest of our app.

**Review by tkz-ld — APPROVED** [review]

**Review by eddanger — APPROVED** [review]

**Comment by chrt00** [comment]
From what I've experienced the rules being too strict increase indirection.

**Review by larry-reid-lendesk — APPROVED** [review]
Thanks for this PR, @chrt00 !

**Pull request merged**
